import type { CircuitJson } from "circuit-json"

export function createTraceAnchoredNetLabelCollisionCircuitJson(): CircuitJson {
  return [
    {
      type: "source_component",
      source_component_id: "source_component_j_eth",
      ftype: "simple_chip",
      name: "J_ETH",
    },
    {
      type: "source_component",
      source_component_id: "source_component_u3",
      ftype: "simple_chip",
      name: "U3",
    },
    {
      type: "schematic_component",
      schematic_component_id: "schematic_component_j_eth",
      center: { x: 6.5, y: 2.1 },
      size: { width: 2.15, height: 4 },
      source_component_id: "source_component_j_eth",
      is_box_with_pins: true,
      schematic_sheet_id: "schematic_sheet_0",
    },
    {
      type: "schematic_component",
      schematic_component_id: "schematic_component_u3",
      center: { x: 1.65, y: 0.8 },
      size: { width: 1.9, height: 4.2 },
      source_component_id: "source_component_u3",
      is_box_with_pins: true,
      schematic_sheet_id: "schematic_sheet_0",
    },
    {
      type: "schematic_port",
      schematic_port_id: "schematic_port_j_eth_mdi2_n",
      schematic_component_id: "schematic_component_j_eth",
      center: { x: 5, y: 1.3 },
      source_port_id: "source_port_j_eth_mdi2_n",
      facing_direction: "left",
      distance_from_component_edge: 0.4,
      side_of_component: "left",
      pin_number: 1,
      true_ccw_index: 0,
      display_pin_label: "MDI2-",
      is_connected: true,
      schematic_sheet_id: "schematic_sheet_0",
    },
    {
      type: "schematic_port",
      schematic_port_id: "schematic_port_u3_dvdd10",
      schematic_component_id: "schematic_component_u3",
      center: { x: 3, y: 1.3 },
      source_port_id: "source_port_u3_dvdd10",
      facing_direction: "right",
      distance_from_component_edge: 0.4,
      side_of_component: "right",
      pin_number: 1,
      true_ccw_index: 0,
      display_pin_label: "DVDD10",
      is_connected: true,
      schematic_sheet_id: "schematic_sheet_0",
    },
    {
      type: "schematic_port",
      schematic_port_id: "schematic_port_u3_avdd103",
      schematic_component_id: "schematic_component_u3",
      center: { x: 3, y: 1.9 },
      source_port_id: "source_port_u3_avdd103",
      facing_direction: "right",
      distance_from_component_edge: 0.4,
      side_of_component: "right",
      pin_number: 2,
      true_ccw_index: 1,
      display_pin_label: "AVDD103",
      is_connected: true,
      schematic_sheet_id: "schematic_sheet_0",
    },
    {
      type: "schematic_trace",
      schematic_trace_id: "schematic_trace_u3_vdd",
      source_trace_id: "source_trace_u3_vdd",
      edges: [
        { from: { x: 3, y: 1.9 }, to: { x: 4.3, y: 1.9 } },
        { from: { x: 4.3, y: 1.9 }, to: { x: 4.3, y: 1.3 } },
        { from: { x: 4.3, y: 1.3 }, to: { x: 3, y: 1.3 } },
      ],
      junctions: [],
      schematic_sheet_id: "schematic_sheet_0",
    },
    {
      type: "schematic_net_label",
      schematic_net_label_id: "schematic_net_label_eth_mdi2_n",
      text: "ETH_MDI2_N",
      source_net_id: "source_net_eth_mdi2_n",
      anchor_position: { x: 5, y: 1.3 },
      center: { x: 4.34, y: 1.3 },
      anchor_side: "right",
      schematic_sheet_id: "schematic_sheet_0",
    },
    {
      type: "schematic_net_label",
      schematic_net_label_id: "schematic_net_label_rtl_vdd_1v0",
      text: "RTL_VDD_1V0",
      source_net_id: "source_net_rtl_vdd_1v0",
      anchor_position: { x: 4.3, y: 1.3 },
      center: { x: 5.02, y: 1.3 },
      anchor_side: "left",
      schematic_sheet_id: "schematic_sheet_0",
    },
  ]
}
