name: bun-formatcheck

on:
  push:
  pull_request:

jobs:
  formatcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run format check
        run: bun run format:check
